#!/usr/bin/env python2
import fileinput, time
packagelist = []
unique = set()
for line in fileinput.input():
    s = line.split()
    d = s[0].split('|')
    packagelist.append({'dist': d[0], 'comp': d[1], 'pkg': s[1], 'ver': s[2], 
        'arch': d[2][:-1]})
    unique.add(s[1]) # Add the package name into a set
# Sort everything by package name
packagelist.sort(key=lambda k: k['pkg'])

print """<!DOCTYPE HTML>
<html>
<!-- This page was generated by a python script, converting reprepro's list output
into a nice HTML table: source is available at https://github.com/GLolol/codescraps/blob/master/packagelists/pparse.py -->
<head><title>Package List for GLolol's Utopia Repository</title>
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="gstyle.css">
</head>
<body>
<table>
<tr>
<th>Package Name</th>
<th>Component</th>
<th>Version</th>
<th>Architecture</th>
</tr>"""
for p in packagelist:
    print("""<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>"""
        .format(p.get('pkg'), p.get('comp'),
        p.get('ver'), p.get('arch')))
print """</table>
<p><b>Total items:</b> {} ({} unique package names)</p>
<p>Last updated {}</p>
</body></html>""".format(len(packagelist), len(unique), time.strftime("%I:%M:%S %p, %b %d %Y +0000", time.gmtime()))
